name: CI

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  CI: true
  NODE_VERSION: 16

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.22.0
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
      - name: Install & cache node dependencies
        uses: ./.github/actions/install
      - run: pnpm run lint
  type:
    name: Type
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.22.0
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
      - name: Install & cache node dependencies
        uses: ./.github/actions/install
      - name: Typescript checks
        run: pnpm run typecheck

  circular:
    name: Circular
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.22.0
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
      - name: Install & cache node dependencies
        uses: ./.github/actions/install
      - run: pnpm run test-circular

  test-build-front:
    name: Test Build Front ⚙️
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/documentation
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install & cache node dependencies
        uses: ./.github/actions/install

      - name: Install FrontEnd dependencies
        run: pnpm i

      - name: Build app
        run: pnpm run build
