name: Tests E2E 🧪

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read
  actions: read

env:
  CI: true
  NODE_VERSION: 16

defaults:
  run:
    shell: bash
    working-directory: ./tests-e2e

jobs:
  test-e2e:
    name: Test E2E 🧪
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Copy CI env vars
        run: cp .env.ci .env

      - name: Install & cache node dependencies
        uses: ./.github/actions/install

      - name: Install E2E dependencies
        run: pnpm i

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::885330630487:role/github-action
          aws-region: eu-west-1

      - name: Deploy app
        run: pnpm run deploy

      - name: Run tests
        run: pnpm run test
